create table advertisements
(
    ID       INTEGER generated by default as identity primary key,
    DATE     TIMESTAMP                   not null,
    TYPE    CHARACTER VARYING(250) not null,
    TITLE    CHARACTER VARYING(250) not null,
    DESCRIPTION    CHARACTER VARYING(4000) not null,
    PRICE   NUMERIC(6, 2)          not null,
    CATEGORIES CHARACTER VARYING(250) not null,
    IMAGES    CHARACTER VARYING(500) not null
);
